---
title: "MLB Stuff Plus - Fastballs"
author: "Carl Foust"
date: "`r Sys.Date()`"
output: html_document
---

# TODO
- Adjusted VAA and HAA
- Cutter, Breaking Ball or Fastball?
- Splinker to Splitter


```{r setup, include=FALSE}
# Data Manipulation
library(tidyverse)

# Modeling
library(tidymodels)
library(xgboost)
library(vip)
library(doParallel)
library(probably)

# SQL
library(RPostgres)

# Load Functions
source("../utils.R")

wd <- getwd()
set.seed(1015)
```

```{r}
.vaa_model = load_model_xgb("exp_vaa_XGBoost_2025-12-24_12-28.json")
.haa_model = load_model_xgb("exp_haa_XGBoost_2025-12-24_14-31.json")
.arm_angle_model = load_model_xgb("exp_arm_angle_XGBoost_2025-12-24_16-43.json")
.exp_ff_avert_model = load_model_xgb("exp_ff_az_XGBoost_2026-01-06_00-04.json")
.exp_ff_ahorz_model = load_model_xgb("exp_ff_ahorz_XGBoost_2026-01-19_21-30.json")
.exp_si_avert_model = load_model_xgb("exp_si_avert_XGBoost_2026-02-16_23-34.json")
.exp_si_ahorz_model = load_model_xgb("exp_si_ahorz_XGBoost_2026-02-17_00-02.json")
.exp_ct_avert_model = load_model_xgb("exp_ct_avert_XGBoost_2026-02-16_22-01.json")
.exp_ct_ahorz_model = load_model_xgb("exp_ct_ahorz_XGBoost_2026-02-16_22-34.json")
```

```{r}
con <- dbConnect(Postgres(), 
                 user = "postgres", 
                 host = "localhost", 
                 db = "baseball-research")

training_sql <- "SELECT * FROM statcast_pitching_dev WHERE game_year >= 2022 AND game_type = 'R'"

# testing_sql <- "SELECT * FROM statcast_pitching_dev WHERE game_year >= 2025 AND game_type = 'R'"

data_train <- dbGetQuery(con, training_sql)
# data_test <- dbGetQuery(con, testing_sql) |> filter(game_year > 2024)

```

```{r data-processing}
processed_data_train <- create_advance_metrics(data_train)

# processed_data_test <- create_advance_metrics(data_test)
```

```{r data-processing}
vaa_preds <- generate_model_preds(model = .vaa_model,
                                  data = processed_data_train,
                                  features = vaa_features,
                                  output_name = "xVAA")

haa_preds <- generate_model_preds(model = .haa_model,
                                  data = processed_data_train,
                                  features = haa_features,
                                  output_name = "xHAA")

arm_angle_preds <- generate_model_preds(model = .arm_angle_model,
                                        data = processed_data_train,
                                        features = arm_angle_features,
                                        output_name = "exp_arm_angle")

exp_ff_avert_preds <- generate_model_preds(model = .exp_ff_avert_model,
                                        data = processed_data_train,
                                        features = exp_ff_features,
                                        output_name = "exp_ff_avert")

exp_ff_ahorz_preds <- generate_model_preds(model = .exp_ff_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_ff_ahorz")

exp_si_avert_preds <- generate_model_preds(model = .exp_si_avert_model,
                                        data = processed_data_train,
                                        features = exp_ff_features,
                                        output_name = "exp_si_avert")

exp_si_ahorz_preds <- generate_model_preds(model = .exp_si_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_si_ahorz")

exp_ct_avert_preds <- generate_model_preds(model = .exp_ct_avert_model,
                                        data = processed_data_train,
                                        features = exp_ff_features,
                                        output_name = "exp_ct_avert")

exp_ct_ahorz_preds <- generate_model_preds(model = .exp_ct_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_ct_ahorz")

processed_data_train <- bind_cols(processed_data_train, 
                                  vaa_preds, 
                                  haa_preds, 
                                  arm_angle_preds, 
                                  exp_ff_avert_preds,
                                  exp_ff_ahorz_preds,
                                  exp_si_avert_preds,
                                  exp_si_ahorz_preds,
                                  exp_ct_avert_preds,
                                  exp_ct_ahorz_preds)

pitching_processed <- processed_data_train |> 
  mutate(arm_angle_savant = arm_angle,
         arm_angle = ifelse(is.na(arm_angle), exp_arm_angle, arm_angle)) |> 
  mutate(swing = case_when(description %in% swing_list ~ TRUE, TRUE ~ 0),
         whiff = case_when(description %in% whiff_list ~ TRUE, TRUE ~ 0),
         foul = case_when(description %in% foul_list ~ TRUE, TRUE ~ 0),
         #BIP = case_when(description %in% BIP ~ TRUE, TRUE ~ 0)
         bip = launch_speed_angle) %>% 
  mutate(exp_ahorz = case_when(pitch_name == "4-Seam Fastball" ~ exp_ff_ahorz,
                               pitch_name == "Sinker" ~ exp_si_ahorz,
                               pitch_name == "Cutter" ~ exp_ct_ahorz,
                               TRUE ~ NA_real_),
         exp_avert = case_when(pitch_name == "4-Seam Fastball" ~ exp_ff_avert,
                               pitch_name == "Sinker" ~ exp_si_avert,
                               pitch_name == "Cutter" ~ exp_ct_avert,
                               TRUE ~ NA_real_),
         diff_exp_ahorz = a_horz - exp_ahorz,
         diff_exp_avert = a_vert - exp_avert)
```

```{r}
# hhh=pitching_processed %>% select(pitcher:pitch_group, a_horz, a_vert, xVAA:diff_exp_avert) %>% filter(pitch_group == "Fastball") %>% group_by(pitcher, pitch_name) %>% summarise(n=n(), ahorz = round(mean(a_horz), 1), avert = round(mean(a_vert), 1), exp_ff_ahorz = round(mean(exp_ff_ahorz),1), exp_ff_avert = round(mean(exp_ff_avert),1), exp_si_ahorz = round(mean(exp_si_ahorz),1), exp_si_avert = round(mean(exp_si_avert),1), exp_ct_ahorz = round(mean(exp_ct_ahorz),1), exp_ct_avert = round(mean(exp_ct_avert),1))
# 
# library(baseballr)
# all_players_2025 <- mlb_sports_players(sport_id = 1, season = 2025) %>% 
#   select(player_id, full_name)
# 
# hhhh=hhh %>% rename(player_id = pitcher) %>% left_join(all_players_2025) %>% select(player_id, full_name, pitch_name:exp_ct_avert)


# data_typed <- pitching_processed |> 
#   left_join(Cutter_labeled, by = c("pitcher", "pitch_name", "game_year")) |> 
#   mutate(pitch_group = if_else(pitch_name == "Cutter", new_group, pitch_group)) |> 
#   select(-new_group)
# 
# data_typed <- data_typed |> 
#   left_join(FB_avg |> select(-c(n)), by = c('pitcher', "game_year")) |> 
#   mutate(RelSpeedDiff = release_speed - FBvelo,
#          Horz_Accel_Diff = a_horz - FBhbreak,
#          Vert_Accel_Diff = a_vert - FBvbreak,
#          launch_speed_angle = ifelse(is.na(launch_speed_angle), 0, launch_speed_angle))

```

```{r}

processed_data = pitching_processed |> 
  filter(pitch_group == "Fastball",
         swing == 1)

# vprocessedData = pitching_processed |> 
#   filter(PitchGroup == "Fastball")

model_data = processed_data |> 
  select(pitcher, game_date, pitch_name, is_lhh, p_throws,
         release_speed, release_spin_rate, release_extension, release_pos_x, release_pos_z, 
         a_vert, diff_exp_avert, a_horz, diff_exp_ahorz,
         spin_axis, arm_angle, xVAA, xHAA, 
         # rel_speed_fb_diff, a_horz_fb_diff, a_vert_fb_diff,
         # exp_ff_ax, exp_ff_avert, 
         swing, whiff, foul, bip)

model_data_rhp = model_data |> 
  filter(p_throws == 1) |> 
  rowid_to_column("ID") |> 
  select(-c(p_throws, game_date, pitch_name, pitcher))

model_data_lhp = model_data |> 
  filter(p_throws == 0) |> 
  rowid_to_column("ID") |> 
  select(-c(p_throws, game_date, pitch_name, pitcher))

```

```{r}

```

```{r}

modelPrep = function(dataFrame, pitchType, outcomeType){
  if (outcomeType == "Whiff"){
    data = dataFrame |> 
      #filter(Swing == 1) |> 
      mutate(label = as.factor(whiff)) |> 
      select(-c(ID, swing, whiff, foul, bip))
    
  } else if (outcomeType == "Foul"){
    data = dataFrame |> 
      #filter(Whiff == 0) |> 
      mutate(label = as.factor(foul)) |> 
      select(-c(ID, swing, whiff, foul, bip))
    
  } else if (outcomeType == "BIP"){
    data = dataFrame |> 
      filter(bip != 0) |> 
      mutate(label = as.factor(bip - 1)) |> 
      select(-c(ID, swing, whiff, foul, bip))
    
  } else {
    print("Invalid Outcome Type: (Whiff, Foul, BIP)")
    stop()
  }
}

```

```{r}
RHP_FF_Whiff_Data = modelPrep(model_data_rhp, "Fastball", "Whiff")
RHP_FF_Foul_Data = modelPrep(model_data_rhp, "Fastball", "Foul")
RHP_FF_BIP_Data = modelPrep(model_data_rhp, "Fastball", "BIP")

LHP_FF_Whiff_Data = modelPrep(model_data_lhp, "Fastball", "Whiff")
LHP_FF_Foul_Data = modelPrep(model_data_lhp, "Fastball", "Foul")
LHP_FF_BIP_Data = modelPrep(model_data_lhp, "Fastball", "BIP")

train_classification_model(RHP_FF_Whiff_Data, "rhp_ff_whiff", tune_no_improve = 25)
train_classification_model(RHP_FF_Foul_Data, "rhp_ff_foul", tune_no_improve = 25)
train_multi_classification_model(RHP_FF_BIP_Data, "rhp_ff_bip", tune_no_improve = 25)

train_classification_model(LHP_FF_Whiff_Data, "lhp_ff_whiff", tune_no_improve = 25)
train_classification_model(LHP_FF_Foul_Data, "lhp_ff_foul", tune_no_improve = 25)
train_multi_classification_model(LHP_FF_BIP_Data, "lhp_ff_bip", tune_no_improve = 25)
```

