---
title: "MLB Quality Plus - Fastballs"
author: "Carl Foust"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Data Manipulation
library(tidyverse)

# Modeling
library(tidymodels)
library(xgboost)
library(vip)
library(doParallel)
library(probably)

# SQL
library(RPostgres)

# Load Functions
source("../utils.R")

wd <- getwd()
set.seed(1015)
```

```{r}
.vaa_model = load_model_xgb("exp_vaa_XGBoost_2025-12-24_12-28.json")
.haa_model = load_model_xgb("exp_haa_XGBoost_2025-12-24_14-31.json")
.arm_angle_model = load_model_xgb("exp_arm_angle_XGBoost_2025-12-24_16-43.json")
.exp_ff_avert_model = load_model_xgb("exp_ff_az_XGBoost_2026-01-06_00-04.json")
.exp_ff_ahorz_model = load_model_xgb("exp_ff_ahorz_XGBoost_2026-01-19_21-30.json")
.exp_si_avert_model = load_model_xgb("exp_si_avert_XGBoost_2026-02-16_23-34.json")
.exp_si_ahorz_model = load_model_xgb("exp_si_ahorz_XGBoost_2026-02-17_00-02.json")
.exp_ct_avert_model = load_model_xgb("exp_ct_avert_XGBoost_2026-02-16_22-01.json")
.exp_ct_ahorz_model = load_model_xgb("exp_ct_ahorz_XGBoost_2026-02-16_22-34.json")
```

```{r}
con <- dbConnect(Postgres(),
                 user = "postgres",
                 host = "localhost",
                 db = "baseball-research")

training_sql <- "SELECT * FROM statcast_pitching_dev WHERE game_year >= 2022 AND game_type = 'R'"

data_train <- dbGetQuery(con, training_sql)
```

```{r data-processing}
processed_data_train <- create_advance_metrics(data_train)
```

```{r data-processing}
vaa_preds <- generate_model_preds(model = .vaa_model,
                                  data = processed_data_train,
                                  features = vaa_features,
                                  output_name = "xVAA")

haa_preds <- generate_model_preds(model = .haa_model,
                                  data = processed_data_train,
                                  features = haa_features,
                                  output_name = "xHAA")

arm_angle_preds <- generate_model_preds(model = .arm_angle_model,
                                        data = processed_data_train,
                                        features = arm_angle_features,
                                        output_name = "exp_arm_angle")

exp_ff_avert_preds <- generate_model_preds(model = .exp_ff_avert_model,
                                           data = processed_data_train,
                                           features = exp_ff_features,
                                           output_name = "exp_ff_avert")

exp_ff_ahorz_preds <- generate_model_preds(model = .exp_ff_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_ff_ahorz")

exp_si_avert_preds <- generate_model_preds(model = .exp_si_avert_model,
                                           data = processed_data_train,
                                           features = exp_ff_features,
                                           output_name = "exp_si_avert")

exp_si_ahorz_preds <- generate_model_preds(model = .exp_si_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_si_ahorz")

exp_ct_avert_preds <- generate_model_preds(model = .exp_ct_avert_model,
                                           data = processed_data_train,
                                           features = exp_ff_features,
                                           output_name = "exp_ct_avert")

exp_ct_ahorz_preds <- generate_model_preds(model = .exp_ct_ahorz_model,
                                           data = processed_data_train,
                                           features = exp_ff_x_features,
                                           output_name = "exp_ct_ahorz")

processed_data_train <- bind_cols(processed_data_train,
                                  vaa_preds,
                                  haa_preds,
                                  arm_angle_preds,
                                  exp_ff_avert_preds,
                                  exp_ff_ahorz_preds,
                                  exp_si_avert_preds,
                                  exp_si_ahorz_preds,
                                  exp_ct_avert_preds,
                                  exp_ct_ahorz_preds)

pitching_processed <- processed_data_train |>
  mutate(arm_angle_savant = arm_angle,
         arm_angle = ifelse(is.na(arm_angle), exp_arm_angle, arm_angle)) |>
  mutate(swing = case_when(description %in% swing_list ~ TRUE, TRUE ~ 0),
         whiff = case_when(description %in% whiff_list ~ TRUE, TRUE ~ 0),
         foul = case_when(description %in% foul_list ~ TRUE, TRUE ~ 0),
         bip = launch_speed_angle,
         called_strike = case_when(description == 'called_strike' ~ TRUE, TRUE ~ 0),
         hbp = case_when(description == 'hit_by_pitch' ~ TRUE, TRUE ~ 0)) |>
  mutate(exp_ahorz = case_when(pitch_name == "4-Seam Fastball" ~ exp_ff_ahorz,
                               pitch_name == "Sinker" ~ exp_si_ahorz,
                               pitch_name == "Cutter" ~ exp_ct_ahorz,
                               TRUE ~ NA_real_),
         exp_avert = case_when(pitch_name == "4-Seam Fastball" ~ exp_ff_avert,
                               pitch_name == "Sinker" ~ exp_si_avert,
                               pitch_name == "Cutter" ~ exp_ct_avert,
                               TRUE ~ NA_real_),
         diff_exp_ahorz = a_horz - exp_ahorz,
         diff_exp_avert = a_vert - exp_avert)
```

```{r}
vprocessedData = pitching_processed |>
  filter(pitch_group == "Fastball")

# Swing-filtered data for Whiff/Foul/BIP models
model_data_swing = vprocessedData |>
  filter(swing == 1) |>
  select(pitcher, game_date, pitch_name, is_lhh, p_throws,
         release_speed, release_spin_rate, release_extension, release_pos_x, release_pos_z,
         a_vert, diff_exp_avert, a_horz, diff_exp_ahorz,
         spin_axis, arm_angle, xVAA, xHAA,
         plate_x, plate_z, sz_top, sz_bot, dist_from_mid,
         swing, whiff, foul, bip, called_strike, hbp)

# All-pitch data for CalledStrike/HBP models
model_data_all = vprocessedData |>
  select(pitcher, game_date, pitch_name, is_lhh, p_throws,
         release_speed, release_spin_rate, release_extension, release_pos_x, release_pos_z,
         a_vert, diff_exp_avert, a_horz, diff_exp_ahorz,
         spin_axis, arm_angle, xVAA, xHAA,
         plate_x, plate_z, sz_top, sz_bot, dist_from_mid,
         swing, whiff, foul, bip, called_strike, hbp)

model_data_swing_rhp = model_data_swing |>
  filter(p_throws == 1) |>
  rowid_to_column("ID") |>
  select(-c(p_throws, game_date, pitch_name, pitcher))

model_data_swing_lhp = model_data_swing |>
  filter(p_throws == 0) |>
  rowid_to_column("ID") |>
  select(-c(p_throws, game_date, pitch_name, pitcher))

model_data_all_rhp = model_data_all |>
  filter(p_throws == 1) |>
  rowid_to_column("ID") |>
  select(-c(p_throws, game_date, pitch_name, pitcher))

model_data_all_lhp = model_data_all |>
  filter(p_throws == 0) |>
  rowid_to_column("ID") |>
  select(-c(p_throws, game_date, pitch_name, pitcher))
```

```{r}
modelPrep = function(dataFrame, outcomeType){
  if (outcomeType == "Whiff"){
    data = dataFrame |>
      mutate(label = as.factor(whiff)) |>
      select(-c(ID, swing, whiff, foul, bip, called_strike, hbp))

  } else if (outcomeType == "Foul"){
    data = dataFrame |>
      mutate(label = as.factor(foul)) |>
      select(-c(ID, swing, whiff, foul, bip, called_strike, hbp))

  } else if (outcomeType == "BIP"){
    data = dataFrame |>
      filter(bip != 0) |>
      mutate(label = as.factor(bip - 1)) |>
      select(-c(ID, swing, whiff, foul, bip, called_strike, hbp))

  } else if (outcomeType == "CalledStrike"){
    data = dataFrame |>
      mutate(label = as.factor(called_strike)) |>
      select(-c(ID, swing, whiff, foul, bip, called_strike, hbp))

  } else if (outcomeType == "HBP"){
    data = dataFrame |>
      mutate(label = as.factor(hbp)) |>
      select(-c(ID, swing, whiff, foul, bip, called_strike, hbp))

  } else {
    print("Invalid Outcome Type: (Whiff, Foul, BIP, CalledStrike, HBP)")
    stop()
  }
}
```

```{r}
RHP_FF_Whiff_Data = modelPrep(model_data_swing_rhp, "Whiff")
RHP_FF_Foul_Data = modelPrep(model_data_swing_rhp, "Foul")
RHP_FF_BIP_Data = modelPrep(model_data_swing_rhp, "BIP")

LHP_FF_Whiff_Data = modelPrep(model_data_swing_lhp, "Whiff")
LHP_FF_Foul_Data = modelPrep(model_data_swing_lhp, "Foul")
LHP_FF_BIP_Data = modelPrep(model_data_swing_lhp, "BIP")

RHP_FF_CS_Data = modelPrep(model_data_all_rhp, "CalledStrike")
RHP_FF_HBP_Data = modelPrep(model_data_all_rhp, "HBP")

LHP_FF_CS_Data = modelPrep(model_data_all_lhp, "CalledStrike")
LHP_FF_HBP_Data = modelPrep(model_data_all_lhp, "HBP")
```

```{r}
train_classification_model(RHP_FF_Whiff_Data, "rhp_ff_qual_whiff", tune_no_improve = 25)
train_classification_model(RHP_FF_Foul_Data, "rhp_ff_qual_foul", tune_no_improve = 25)
train_multi_classification_model(RHP_FF_BIP_Data, "rhp_ff_qual_bip", tune_no_improve = 25)

train_classification_model(LHP_FF_Whiff_Data, "lhp_ff_qual_whiff", tune_no_improve = 25)
train_classification_model(LHP_FF_Foul_Data, "lhp_ff_qual_foul", tune_no_improve = 25)
train_multi_classification_model(LHP_FF_BIP_Data, "lhp_ff_qual_bip", tune_no_improve = 25)

train_classification_model(RHP_FF_CS_Data, "rhp_ff_qual_cs", tune_no_improve = 25)
train_classification_model(RHP_FF_HBP_Data, "rhp_ff_qual_hbp", tune_no_improve = 25)

train_classification_model(LHP_FF_CS_Data, "lhp_ff_qual_cs", tune_no_improve = 25)
train_classification_model(LHP_FF_HBP_Data, "lhp_ff_qual_hbp", tune_no_improve = 25)
```
